### ISSUE TITLE
Have this helper related error in the console when I try to reset mines in instant mode

### ISSUE THREAD

**Issue by TeamRaZeR** [Drawethree/UltraPrisonCore#36]
I haven't tried gradul mode yet.
Here is the bug report:

[18:41:41 ERROR]: [helper] Exception occurred in a helper promise chain
me.lucko.helper.internal.exception.types.PromiseChainException: Exception occurred in a helper promise chain
        at me.lucko.helper.internal.exception.HelperExceptions.reportPromise(HelperExceptions.java:68) ~[helper.jar:?]
        at me.lucko.helper.promise.HelperPromise$SupplyRunnable.run(HelperPromise.java:674) ~[helper.jar:?]
        at me.lucko.helper.internal.exception.HelperExceptions$SchedulerWrappedRunnable.run(HelperExceptions.java:89) ~[helper.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-42]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.jar:git-Paper-42]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[paper-1.19.jar:git-Paper-42]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-42]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-42]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-42]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-42]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: weigher returned a negative number
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
        at me.lucko.helper.random.RandomSelectorImpl.weighted(RandomSelectorImpl.java:63) ~[helper.jar:?]
        at me.lucko.helper.random.RandomSelector.weighted(RandomSelector.java:71) ~[helper.jar:?]
        at dev.drawethree.ultraprisoncore.mines.model.mine.reset.InstantReset.reset(InstantReset.java:29) ~[UltraPrisonCore-1.11.3.jar:?]
        at dev.drawethree.ultraprisoncore.mines.managers.MineManager.lambda$resetMine$8(MineManager.java:364) ~[UltraPrisonCore-1.11.3.jar:?]
        at me.lucko.helper.utils.Delegates$RunnableToSupplier.get(Delegates.java:127) ~[helper.jar:?]
        at me.lucko.helper.promise.HelperPromise$SupplyRunnable.run(HelperPromise.java:672) ~[helper.jar:?]
        ... 9 more

**Comment by TeamRaZeR** [comment]
I have updated Paper and it still has a problem.
[18:54:04 ERROR]: [helper] Exception occurred in a helper promise chain
me.lucko.helper.internal.exception.types.PromiseChainException: Exception occurred in a helper promise chain
        at me.lucko.helper.internal.exception.HelperExceptions.reportPromise(HelperExceptions.java:68) ~[helper.jar:?]
        at me.lucko.helper.promise.HelperPromise$SupplyRunnable.run(HelperPromise.java:674) ~[helper.jar:?]
        at me.lucko.helper.internal.exception.HelperExceptions$SchedulerWrappedRunnable.run(HelperExceptions.java:89) ~[helper.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-50]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.jar:git-Paper-50]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[paper-1.19.jar:git-Paper-50]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-50]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-50]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-50]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-50]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: weigher returned a negative number
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
        at me.lucko.helper.random.RandomSelectorImpl.weighted(RandomSelectorImpl.java:63) ~[helper.jar:?]
        at me.lucko.helper.random.RandomSelector.weighted(RandomSelector.java:71) ~[helper.jar:?]
        at dev.drawethree.ultraprisoncore.mines.model.mine.reset.InstantReset.reset(InstantReset.java:29) ~[UltraPrisonCore-1.11.3.jar:?]
        at dev.drawethree.ultraprisoncore.mines.managers.MineManager.lambda$resetMine$8(MineManager.java:364) ~[UltraPrisonCore-1.11.3.jar:?]
        at me.lucko.helper.utils.Delegates$RunnableToSupplier.get(Delegates.java:127) ~[helper.jar:?]
        at me.lucko.helper.promise.HelperPromise$SupplyRunnable.run(HelperPromise.java:672) ~[helper.jar:?]
        ... 9 more

**Comment by TeamRaZeR** [comment]
I have an outdated version of the plugin gonna download new one maybe it will solve it and I will come back

**Comment by TeamRaZeR** [comment]
I have updated to 1.11.14 and it works perfectly :)
