### ISSUE TITLE
Gems pay

### ISSUE THREAD

**Issue by SbirTeo** [Drawethree/UltraPrisonCore#5]
[21:27:03 INFO]: SbirTeo issued server command: /gems pay Adr_oh 1
[21:27:03 ERROR]: [helper] [SCHEDULER] Exception thrown whilst executing task
[21:27:03 WARN]: java.lang.IllegalStateException: UltraPrisonPlayerGemsReceiveEvent may only be triggered synchronously.
[21:27:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:612)
[21:27:03 WARN]:        at me.lucko.helper.Events.call(Events.java:129)
[21:27:03 WARN]:        at me.drawethree.ultraprisoncore.gems.managers.GemsManager.giveGems(GemsManager.java:144)
[21:27:03 WARN]:        at me.drawethree.ultraprisoncore.gems.managers.GemsManager.lambda$payGems$11(GemsManager.java:193)
[21:27:03 WARN]:        at me.lucko.helper.utils.Delegates$RunnableToSupplier.get(Delegates.java:127)
[21:27:03 WARN]:        at me.lucko.helper.promise.HelperPromise$SupplyRunnable.run(HelperPromise.java:677)
[21:27:03 WARN]:        at me.lucko.helper.scheduler.HelperExecutors$SchedulerWrappedRunnable.run(HelperExecutors.java:95)
[21:27:03 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:26:57 WARN]:        at me.drawethree.ultraprisoncore.gems.managers.GemsManager.lambda$payGems$11(GemsManager.java:193)
[21:26:57 WARN]:        at me.lucko.helper.utils.Delegates$RunnableToSupplier.get(Delegates.java:127)
[21:26:57 WARN]:        at me.lucko.helper.promise.HelperPromise$SupplyRunnable.run(HelperPromise.java:677)
[21:26:57 WARN]:        at me.lucko.helper.scheduler.HelperExecutors$SchedulerWrappedRunnable.run(HelperExecutors.java:95)
[21:26:57 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:26:57 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[21:26:57 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by SbirTeo** [comment]
[21:30:17 ERROR]: [helper] [SCHEDULER] Exception thrown whilst executing task
[21:30:17 WARN]: java.lang.IllegalStateException: UltraPrisonPlayerGemsReceiveEvent may only be triggered synchronously.
[21:30:17 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:612)
[21:30:17 WARN]:        at me.lucko.helper.Events.call(Events.java:129)
[21:30:17 WARN]:        at me.drawethree.ultraprisoncore.gems.managers.GemsManager.giveGems(GemsManager.java:144)
[21:30:17 WARN]:        at me.drawethree.ultraprisoncore.gems.managers.GemsManager.lambda$payGems$11(GemsManager.java:193)
[21:30:17 WARN]:        at me.lucko.helper.utils.Delegates$RunnableToSupplier.get(Delegates.java:127)
[21:30:17 WARN]:        at me.lucko.helper.promise.HelperPromise$SupplyRunnable.run(HelperPromise.java:677)
[21:30:17 WARN]:        at me.lucko.helper.scheduler.HelperExecutors$SchedulerWrappedRunnable.run(HelperExecutors.java:95)
[21:30:17 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[21:30:17 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[21:30:17 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Drawethree** [comment]
Hello, will be delivered in 1.5.1 Update.
